config/routes.rb
Rails.application.routes.draw do
  root "vehicles#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    post '/login_with_phone_number', to: 'users/sessions#login_with_phone_number', as: :login_with_phone_number
    get '/otp_page', to: 'users/sessions#otp_page', as: :otp_page
    post '/verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end
  resources :vehicles, only: [:index, :show]
  resources :bookings

  namespace :admin do
    get 'dashboard', to: 'dashboard#index' # Define the admin dashboard route
    resources :owners, only: [:index]
    resources :vehicles, only: [:index, :show] do
      member do
        patch :verify
        patch :unverify
      end
    end
    resources :vehicle_types
  end

  resources :vehicles do
    post 'send_message', on: :member
  end

  namespace :owners do
    get 'dashboard', to: 'dashboard#index'
    resources :vehicles
    resources :bookings do
      member do
        patch :accept
        patch :reject
      end
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController
	def index; end
end

app/controllers/owners/dashboard_controller.rb
class Owners::DashboardController < OwnersController

  def index
    @vehicles = Vehicle.includes(:owner, :vehicle_type, vehicle_images_attachments: :blob, documents_attachments: :blob).where(owner_id: current_user.id) if current_user.is_owner?
  end

end

app/views/admin/dashboard/index.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to admin_owners_path, class: 'text-decoration-none text-white' do %>
      <div class="card mb-4 text-center text-white bg-primary shadow">
				<div class="card-body">
					<div>
						<div class="fs-4 fw-semibold">
							<%= Owner.count %>
							<div>Owners</div>
						</div>
					</div>
				</div>
			</div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to admin_vehicle_types_path, class: 'text-decoration-none' do %>
      <div class="card mb-4 text-center text-white bg-primary shadow">
        <div class="card-body">
          <div>
						<div class="fs-4 fw-semibold">
							<%= VehicleType.count %> 
							<div>Vehicle Types</div>
						</div>
					</div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to admin_vehicles_path, class: 'text-decoration-none' do %>
      <div class="card mb-4 text-center text-white bg-primary shadow">
        <div class="card-body">
          <div>
						<div class="fs-4 fw-semibold">
							<%= Vehicle.count %> 
							<div>Vehicle</div>
						</div>
					</div>
        </div>
      </div>
    <% end %>
  </div>
</div>