config/routes.rb
Rails.application.routes.draw do
  root "vehicles#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  devise_scope :user do
    post '/login_with_phone_number', to: 'users/sessions#login_with_phone_number', as: :login_with_phone_number
    get '/otp_page', to: 'users/sessions#otp_page', as: :otp_page
    post '/verify_otp', to: 'users/sessions#verify_otp', as: :verify_otp
  end
  resources :vehicles, only: [:index, :show]
  resources :bookings

  namespace :admin do
    get 'dashboard', to: 'dashboard#index' # Define the admin dashboard route
    resources :owners, only: [:index]
    resources :vehicles, only: [:index, :show] do
      member do
        patch :verify
        patch :unverify
      end
    end
    resources :vehicle_types
  end

  resources :vehicles do
    post 'send_message', on: :member
  end

  namespace :owners do
    get 'dashboard', to: 'dashboard#index'
    resources :vehicles
    resources :bookings do
      member do
        patch :accept
        patch :reject
      end
    end
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
    # belongs_to :user
    has_many :vehicles

    validates :user_id, presence: true
end

app/controllers/admin/owners_controller.rb
class Admin::OwnersController < AdminController
	def index
		@owners = User.where(role: 'owner')
	end
end

app/controllers/owners/bookings_controller.rb
class Owners::BookingsController < OwnersController
  before_action :authenticate_user!
  before_action :set_booking, only: [:destroy]

  def index
    @bookings = Booking.includes(:vehicle, :user).where(vehicles: { owner_id: current_user.id }).order(created_at: :desc)
  end

  def destroy
    @booking.destroy
    redirect_to owners_bookings_path, notice: "Booking was successfully destroyed."
  end

  def accept
  	@booking = Booking.find(params[:id])
    @booking.update(status: 'accepted')
    render json: { message: 'Booking accepted.' }
  end

  def reject
  	@booking = Booking.find(params[:id])
    @booking.update(status: 'rejected')
    render json: { message: 'Booking rejected.' }
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(
      :user_id,
      :vehicle_id,
      :start_date,
      :end_date,
      :amount,
      :start_time,
      :end_time,
      :status
    )
  end
end

app/controllers/owners/dashboard_controller.rb
class Owners::DashboardController < OwnersController

  def index
    @vehicles = Vehicle.includes(:owner, :vehicle_type, vehicle_images_attachments: :blob, documents_attachments: :blob).where(owner_id: current_user.id) if current_user.is_owner?
  end

end

app/controllers/owners/vehicles_controller.rb
class Owners::VehiclesController < OwnersController
	before_action :authenticate_user!
	before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

	def index
		@vehicles = Vehicle.includes(:owner, :vehicle_type, vehicle_images_attachments: :blob, documents_attachments: :blob).where(owner_id: current_user.id) if current_user.is_owner?
	end

	def new
		@vehicle = Vehicle.new
	end

	def create
		@vehicle = Vehicle.new(vehicle_params) 

		# Save uploaded images directly without relying on params
    if params[:vehicle][:vehicle_images].present?
      params[:vehicle][:vehicle_images].each do |image|
        @vehicle.vehicle_images.attach(image)
      end
    end
    if params[:vehicle][:documents].present?
      params[:vehicle][:documents].each do |document|
        @vehicle.documents.attach(document)
      end
    end
		if @vehicle.save
			redirect_to owners_vehicle_path(@vehicle), notice: "Vehicle was successfully created."
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@owner = @vehicle.owner
		@related_vehicles = @owner.vehicles.where.not(id: @vehicle.id) # Exclude the current vehicle
	end

	def edit
	end

	def update
    if params[:vehicle][:vehicle_images].present? && (@vehicle.vehicle_images.present? || !@vehicle.vehicle_images.present?)
			params[:vehicle][:vehicle_images].each do |image|
        @vehicle.vehicle_images.attach(image)
      end
		end
		if params[:vehicle][:documents].present? && (@vehicle.documents.present? || !@vehicle.documents.present?)
      params[:vehicle][:documents].each do |document|
        @vehicle.documents.attach(document)
      end
    end
		if @vehicle.update(vehicle_params)
			redirect_to owners_vehicles_path, notice: "Vehicle was successfully updated."
		else
			render :edit, status: :unprocessable_entity			
		end
	end

	def destroy
		@vehicle.destroy
		redirect_to owners_vehicles_path, notice: "Vehicle was successfully destroyed."
	end

	private

	def set_vehicle
		@vehicle = Vehicle.includes(vehicle_images_attachments: :blob).find(params[:id])
	end

	def vehicle_params
		params.require(:vehicle).permit(
			:registration_number,
			:owner_id,
			:vehicle_type_id,
			:base_price,
			:price_per_km,
			:name,
			:fuel_type,
			:cover_image,
			:description
		)
	end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
	layout 'owner'
	before_action :authenticate_user!
	before_action :raise_access_denied

	private
	
  def raise_access_denied
    raise CanCan::AccessDenied.new("Not authorized!", Vehicle) unless current_user && current_user.is_owner?
  end
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/shared/owner/_footer.html.erb
<footer class="footer px-4">
	<div><a href="https://coreui.io">CoreUI </a><a href="https://coreui.io/product/free-bootstrap-admin-template/">Bootstrap Admin Template</a> &copy; 2024 creativeLabs.</div>
	<div class="ms-auto">Powered by&nbsp;<a href="https://coreui.io/docs/">CoreUI UI Components</a></div>
</footer>

app/views/shared/owner/_header.html.erb
<header class="header header-sticky p-0 mb-4">
  <div class="container-fluid border-bottom px-4">
    <button class="header-toggler" type="button" style="margin-inline-start: -14px;">
      <svg class="icon icon-lg">
        <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-menu">
        </use>
      </svg>
    </button>
    <ul class="header-nav d-none d-lg-flex">
      <li class="nav-item">
      	<%= link_to 'Dashboard', owners_dashboard_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="header-nav ms-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg class="icon icon-lg">
            <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-bell">
            </use>
          </svg>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg class="icon icon-lg">
            <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-list-rich">
            </use>
          </svg>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg class="icon icon-lg">
            <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-envelope-open">
            </use>
          </svg>
        </a>
      </li>
    </ul>
    <ul class="header-nav">
      <li class="nav-item py-1">
        <div class="vr h-100 mx-2 text-body text-opacity-75"></div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link py-0 pe-0" data-coreui-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
          <div class="avatar avatar-md"><%= image_tag 'avatars/1.jpg', class:"avatar-img" %> </div>
        </a>
        <div class="dropdown-menu dropdown-menu-end pt-0">
          <div class="dropdown-header bg-body-tertiary text-body-secondary fw-semibold rounded-top mb-2">Account</div>
				  <%= link_to destroy_user_session_path, class: "dropdown-item nav-link" do %>
				    <svg class="icon me-2">
				      <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-account-logout"></use>
				    </svg>
				    Sign Out
				  <% end %>
        </div>
      </li>
    </ul>
  </div>
</header>

app/views/shared/owner/_sidebar.html.erb
<div class="sidebar sidebar-dark sidebar-fixed border-end" id="sidebar" data-controller="sidebar">
  <div class="sidebar-header border-bottom">
    <div class="sidebar-brand">
      <h3><%= current_user.name %></h3>
    </div>
    <button class="btn-close d-lg-none close-btn" type="button" data-coreui-dismiss="offcanvas" data-coreui-theme="dark" aria-label="Close"></button>
  </div>
  <ul class="sidebar-nav" data-coreui="navigation" data-simplebar>
    <li class="nav-item">
      <%= link_to owners_dashboard_path, class: 'nav-link', target: '_top' do %>
      <svg class="nav-icon">
        <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-speedometer">
        </use>
      </svg> Dashboard
      <% end %>
    </li>
    <li class="nav-divider"></li>
    <li class="nav-item">
      <%= link_to new_owners_vehicle_path, class: 'nav-link', target: '_top' do %>
      <svg class="nav-icon">
        <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-speedometer">
        </use>
      </svg> Add Vehicles 
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to owners_bookings_path, class: 'nav-link', target: '_top' do %>
      <svg class="nav-icon">
        <use xlink:href="<%= asset_path('coreui/sprites/free.svg') %>#cil-speedometer">
        </use>
      </svg> Bookings
      <% end %>
    </li>
  </ul>
  <div class="sidebar-footer border-top d-none d-md-flex">
    <button class="sidebar-toggler" type="button" data-coreui-toggle="unfoldable"></button>
  </div>
</div>